### PR TITLE
doc(baseConfig): add auth0 provider documentation

### PR DESCRIPTION
**Pull request by nexbit**
A bit rough but I'm short on time.. Do you think it can suffice?

### CODE REVIEW

**Comment by doktordirk** [comment]
Yeah I think it.s quite cool. Might deserve it.s own md file and some exposure in the overview, but I can do that if you.re short on time

**Comment by nexbit** [comment]
No prob, borrowed some lunch time.. Take a look and see if it fits nicely

**Comment by nexbit** [comment]
Not necessarily. Auth0 gives back an ID token, and the snippet demonstrates how to use it to set a cookie with the same expiration for some other backend use.
in my app I have an openresty (nginx with lua) backend that use the cookie to protect some restricted resources.

**Comment by doktordirk** [comment]
then a storage type 'cookie'? thing is just that the cookie hangs around when login out atm

**Comment by nexbit** [comment]
You're right, in fact I get rid of it after logout, maybe I can include that in the snippet
```
    return this._authService.logout(null)
      .then(() => {
        Cookie.delete('cookie-bearer');
      });
```
Actually I have a far more complicated setup, but the point is that you clear the cookie on logout.
If u find it confusing, feel free to get rid of it in the snippet and leave a simple login method, nothing more..

**Comment by doktordirk** [comment]
threre are some small thing which might need to change after the others PRs are in, but i can do that than. so else :+1:

**Comment by nexbit** [comment]
So do u want me to add that logout code or delete the cookie part or leave that part alone? 8-)

**Comment by doktordirk** [comment]
hmm, i'd certainly keep in in some way (with the logout). only since in theory it's not linked to auth0, it may better be an own section (as file or still within auth0.md if that approach is likely to be most common for auth0)

**Pull request merged**
